### ISSUE TITLE
When I activate ECEnabler kext, display option is missing in Keyboard Shortcuts

### ISSUE THREAD

**Issue by yusfklncc** [1Revenger1/ECEnabler#14]
![image](https://user-images.githubusercontent.com/78423442/140657562-0fcf425a-3c22-4bf3-a518-dec29f6b8e96.png)

Display (Ekran) is missing when I activate ecenabler kext.

**Comment by 1Revenger1** [comment]
Does it disappear when doing manual battery patching?
ECEnabler should have no affect like this, it'd probably be battery status working that would cause this.

**Comment by yusfklncc** [comment]
Yes I tried that. When I use SSDT for battery again the display option disappears. I changed the buttons and enabled ECEnabler so the FN keys now work but the display option is missing. I guess it's not so important anymore.
