### ISSUE TITLE
ECEnabler.kext doesn't work on older macOS versions than High Sierra

### ISSUE THREAD

**Issue by Repama** [1Revenger1/ECEnabler#15]
Hi,

It may be just my laptop's problem but I am not sure. I am having troubles having ECEnabler.kext work on Sierra and older. I am using Mavericks (10.9) now and it still doesn't work. I even tested Sierra (10.12) but it still didn't worked. Is anyone experiencing this problem? And yes i am using the latest version of ECEnabler. Even i just tested older versions but it still didn't work.

**Comment by 1Revenger1** [comment]
Are you able to provide logs?

**Comment by Repama** [comment]
> Are you able to provide logs?

Well sorry for the late answer but i fixed it with a fresh EFI that I maked with OC 0.7.1. I am not sure what i did different but it did fix it.
