### ISSUE TITLE
CrosEC.kext is worked on  Sonoma ,but Mojave doesn't.

### ISSUE THREAD

**Issue by hk860566999** [1Revenger1/ECEnabler#29]
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

/Library/Extensions/CrosEC.kext - no compatible dependency found for as.vit9696.VirtualSMC.
Code Signing Failure: not code signed
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC

Diagnostics for /Library/Extensions/CrosEC.kext:
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC
        
CrosEC.kext is worked on  Sonoma ,but Mojave doesn't.

**Comment by 1Revenger1** [comment]
Closing at this is the repo for ECEnabler, a seperate project from CrosEC.
