### ISSUE TITLE
Cycle count doesn't work on Hp probook 430 g3

### ISSUE THREAD

**Issue by Human7900** [1Revenger1/ECEnabler#7]
Hi
Thank you so much for this awesome kext.
The cycle count on my hp laptop doesn't work. Because of this I am unable to use the macOS powerchime.
Screenshots attached.

![Screen Shot 2021-05-17 at 2 59 24 PM](https://user-images.githubusercontent.com/84245065/118475448-e3e65f80-b729-11eb-8fa2-8e0e246714a8.png)

![Screen Shot 2021-05-17 at 3 29 40 PM](https://user-images.githubusercontent.com/84245065/118475474-ec3e9a80-b729-11eb-8bc1-221c607b35ab.png)

**Comment by 1Revenger1** [comment]
As far as I'm aware, this isn't an issue with ECEnabler. All this does is allow ACPI to read/write fields larger than 8 bits. Check and make sure it isn't something that HP broke in their _BIX method. I've heard that this is broken for a lot of HPs

**Comment by Human7900** [comment]
I do not have any coding skills so I think I will have to live with it . Can you tell me how to check if the _BIX method is broken or not. Thanks once again.
